version: '3'

# Define a custom network for clarity
networks:
  lumosense_net:

services:
  mongo:
    image: mongo
    # Expose the standard Mongo port
    ports:
      - "27017:27017"
    networks:
      - lumosense_net

  backend:
    build: ./backend
    # Publish container port 4000 on host port 4000
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - lumosense_net

  frontend:
    build: ./frontend
    # Publish React static server on host port 3000
    ports:
      - "3000:3000"
    # Environment variable to point to backend via host.docker.internal
    environment:
      - REACT_APP_BACKEND_URL=http://host.docker.internal:4000
    networks:
      - lumosense_net

  node-red:
    image: nodered/node-red
    # Mount the flows.json you will import below
    volumes:
      - ./node-red/flows.json:/data/flows.json
    ports:
      - "1880:1880"
    depends_on:
      - backend
    networks:
      - lumosense_net
